"
" dotphiles : https://github.com/dotphiles/dotphiles
"
" Setup vim and load required plugins before dotvim
"
" Authors:
"   Ben O'Hara <bohara@gmail.com>
"


" Call dotvim
source ~/.vim/dotvim.vim

if has("user_commands")
  set nocompatible
  filetype off
  set rtp+=~/.vim/bundle/vundle/
  call vundle#rc()
  "let g:vundles=['general', 'git', 'hg', 'programming', 'completion', 'ruby', 'python', 'misc']
  "let g:vundles=['general']
  let g:vundles=[]
  "let g:neocomplcache_enable_at_startup = 1
  " Load 'vundles'
  source ~/.vim/vundles.vim
  " Add extra bundles here...
  " Bundle 'reponame'
  Bundle 'chriskempson/base16-vim'
  Plugin 'flazz/vim-colorschemes'
  Bundle 'dag/vim-fish'
  Bundle 'vim-scripts/lh-vim-lib'
  Bundle 'LucHermitte/local_vimrc'
  "Bundle 'rhysd/vim-clang-format'
  Plugin 'google/vim-glaive'
  Plugin 'google/vim-maktaba'
  Plugin 'google/vim-codefmtlib'
  Plugin 'google/vim-codefmt'

  call glaive#Install()

  Glaive codefmt plugin[mappings]=1

endif

" Customize to your needs...
set relativenumber
set tw=79
set formatoptions=tcqn1
set title

set shell=/bin/bash

if has("gui_running")
  set background=light
else
  set background=dark
endif
