#!/bin/bash

find "$HOME/tmp" -type f -mtime +14 -print0 | grep -v .keep | xargs -0 -r rm
find "$HOME/tmp" -type l -mtime +14 -print0 | xargs -0 -r rm
find "$HOME/tmp" -depth -type d -print0 | xargs -0 -r rmdir \
  --ignore-fail-on-non-empty
